### ISSUE TITLE
chore(root): Update script

### ISSUE THREAD

**Issue by seungdeok** [seungdeok/monorepo-template#23]
## Package
root

## Detail
- Configure tsconfig.json
- Update build script
- Update test script
 
## Todo
- [ ] Configure tsconfig.json
- [ ] Update build script
- [ ] Update test script
